effects:
  ui: 29123
  success: 29124
  failure: 29125

# Whether or not the owner must enter the code each time
rememberOwner: true

# Whether or not other users need to enter the code every time
rememberUsers: true

# Whether or not users who aren't the owner can change the lock
nonOwnerCanChangeCode: true

# Whether or not users who do not own the barricade can lock it
onlyOwnerCanLock: false

attempts:
  cooldown: 60 # Cooldown in seconds
  damages:
  - 0 # Occurs on the first attempt
  - 30 # Occurs on the second attempt
  - 50
  - 255 # Max damage. Occurs on the fourth attempt, and all others